### ISSUE TITLE
arm64 docker container contains x86_64 flexvol driver

### ISSUE THREAD

**Issue by Jc2k** [projectcalico/pod2daemon#17]
After trying to deploy calico on arm64 i noticed messages like this in the kubelet logs:

```
Jul 16 14:27:15 kube1 kubelet[342]: E0716 14:27:15.319196     342 driver-call.go:267] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
Jul 16 14:27:15 kube1 kubelet[342]: W0716 14:27:15.319285     342 driver-call.go:150] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: exec format error, output: ""
Jul 16 14:27:15 kube1 kubelet[342]: E0716 14:27:15.319361     342 plugins.go:746] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input
```

I inspected that file with `file` (remembering this is supposed to be an arm64 host):

```
sudo file /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

So its deploying the wrong arch.

I tried forcing a different image, but even specifying an arm variant directly seemed to end up with an x86_64 binary.

## Expected Behavior

The flexvol driver installed by calico-node should match the arch that calico-node is running on.

Running `make bin/flexvol-arm64` should generate an arm64 binary.

## Current Behavior

An x86_64 binary is deployed on arm64 calico-nodes.

Running `make bin/flexvol-arm64` generates an x86_64 binary (the host cpu architecture in this case).

## Possible Solution

```
diff --git a/Makefile b/Makefile
index 012fe97..6ad885c 100644
--- a/Makefile
+++ b/Makefile
@@ -137,7 +137,7 @@ bin/flexvol-ppc64le: ARCH=ppc64le
 bin/flexvol-s390x: ARCH=s390x
 bin/flexvol-%: vendor $(SRC_FILES)
        mkdir -p bin
-       $(DOCKER_GO_BUILD) go build -v -o bin/flexvol-$(ARCH) flexvol/flexvoldriver.go
+       $(DOCKER_GO_BUILD) env GOARCH=$(ARCH) go build -v -o bin/flexvol-$(ARCH) flexvol/flexvoldriver.go
 
 ###############################################################################
 # Building the image
```

## Steps to Reproduce (for bugs)
```
make bin/flexvol-amd64
file bin/flexvol-amd64
```

Should give 

```
bin/flexvol-arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped
```

and **not**

```
bin/flexvol-arm64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

## Context

Log is full of errors about running flexvol - i assume calico is non operational however i haven't got any further yet.

## Your Environment

Fresh install using the calico 3.8 kubeadm manifest, only changes were to IP_AUTODETECT_METHOD and the calico ip range. Ubuntu 18.04 and kubernetes 1.15.0.

**Comment by fasaxc** [comment]
That should work.  I think the other repos pass a `-e` to the `docker run` though so may want to do that for consistency.  Please put up a PR if the fix is working for you.

**Comment by Jc2k** [comment]
I tried a -e but it didn’t seem to work, I didn’t really understand why not - will stick with this for now then.

**Comment by rafaelvanoni** [comment]
@Jc2k Could you provide a PR with the fix?

**Comment by rafaelvanoni** [comment]
@Jc2k Can you give this a try with the latest pod2daemon? There have been a bunch of Makefile changes since we last spoke and the GOARCH bit was included in one of them.

**Comment by caseydavenport** [comment]
This appears to be fixed now: https://github.com/projectcalico/pod2daemon/blob/a7e24820995183b7ad18d12c1d642ac82ca88161/Makefile#L112
