### ISSUE TITLE
uds init error, retcode 1, output: "2019/07/27 12:46:49 Unix syslog delivery error\n"

### ISSUE THREAD

**Issue by cruwe** [projectcalico/pod2daemon#20]
kube-controller-manager dumps into the logs every three minutes

```
E0727 12:37:49.351357       1 driver-call.go:267] Failed to unmarshal output for command: init, output: "2019/07/27 12:37:49 Unix syslog delivery error\n", error: invalid character '/' after top-level value
W0727 12:37:49.351372       1 driver-call.go:150] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: exit status 1, output: "2019/07/27 12:37:49 Unix syslog delivery error\n"
E0727 12:37:49.351384       1 plugins.go:746] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: invalid character '/' after top-level value
```

Executing in the controller-manager container yields
```
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds init
2019/07/27 12:35:31 Unix syslog delivery error
```
the actual value is of course time-dependent.

For comparison, on the host it runs
```
sudo /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds init
{"status":"Success","message":"Init ok.","capabilities":{"attach":false}}
```

## Expected Behaviour

I'd expect uds to run on k8s 1.15.1 successfully.

## Current Behaviour

cf. above

## Steps to Reproduce (for bugs)

1. install ubuntu 18.04
2. install k8s via kubeadm
3. install calico via the released k8s manifests

## Your Environment

System is
- still single-node k8s v1.15.1
- on Ubuntu 18.04 with  4.15.0-54-generic
- zfs on linux v0.8.1 (very probably unrelated, but for completeness sake)
- rsyslog is running, i have checked

**Comment by rafaelvanoni** [comment]
Seems like we need to do some work in our error handling here. Is the volume accessible and working correctly ?

**Comment by vishwakhrushi** [comment]
I'm facing the same kind of issue on my worker nodes.

**Comment by filip-havlicek** [comment]
the same problem with kubernetes 1.15.1 (kubeadm) on Debian Stretch

i have few notes:
 - on freshly installed server directory `/usr/libexec/kubernetes` doesn't exist
 - this directory is (probably) created during the kubeadm init
 - after the first `kubeadm init --config=config.yaml` the directory `/usr/libexec/kubernetes/kubelet-plugins/volume/exec` is not mounted to kube-controller-manager container (i checked it directly in container and in the pod manifest) and I didn't see errors in kube-controller-manager after calico install
 - after `kubeadm init phase control-plane controller-manager --config=config.yaml` the flexvolume directory is mounted and there is one occurence of error messages during controller startup
 - if you reset and init cluster again on the same machine (or if directory `/usr/libexec/kubernetes/kubelet-plugins/volume/exec` pre-exists on the clean machine; the flexvolume directory is mounted in kube-controller-manager container during the cluster init) and install calico, there is flood of error messages in kube-controller-manager log
```
kubeadm reset
rm -r /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
kubeadm init --config=config.yaml
```
 - if you remove kube-controller-manager container directly on the machine (docker stop; docker rm) there is only one occurence of error messages during the controller startup (after the kubelet start it again from the pod manifest)

**Comment by filip-havlicek** [comment]
some idea? still the same issue with the latest calico (v3.8.2) on the kubernetes 1.15.2

**Comment by fasaxc** [comment]
Apart from errors, are there any other symptoms?  The flexvol is used for application layer policy.  If you're not using that feature, is everything else still working?

**Comment by cruwe** [comment]
I did not notice anything not working, so I presume, yes, no other symptoms. Difficult so say with a single node setup, though. I am a tad annoyed at having 55MB logs at 30 days uptime with the controller manager, difficult to find an issue if you have one with that amount, but storage-wise, I can afford that. Otherwise, all is fine.

**Comment by filip-havlicek** [comment]
everything is working fine, as far as i know. even the flexvolume functionality is working (i think... i tested it previously and i will test it tomorrow again, because i'm not sure about it)
just the logs are annoying

**Comment by filip-havlicek** [comment]
i tested flexvolume with this manifest (with some minor changes because of podsecuritypolicy) - https://raw.githubusercontent.com/projectcalico/pod2daemon/master/flexvol/udsver-mount-dummy.yaml
volume was visibly mounted in the container
```
tmpfs           8.0K     0  8.0K   0% /tmp/udsver
tmpfs           395M  108M  287M  28% /tmp/udsver/nodeagent
```
i can't tell if it works correctly or not, but this simple volume mount test was OK

**Comment by FengyunPan2** [comment]
the same problem with kubernetes 1.13.4 (kubeadm) on ubuntu.

**Comment by rafaelvanoni** [comment]
This issue has been addressed in https://github.com/projectcalico/pod2daemon/pull/23 (commit 2214d88667e).
